### PR TITLE
Django-OTP compatibility

### PR DESCRIPTION
**Pull request by an7oine**
* copy OTP status from impersonator to impersonated user

### CODE REVIEW

**Comment by djm** [comment]
Hi Antoine - thanks for the PR but we cannot accept this as we don't use `django-otp` or have a dependency on it. Accepting this would break installs for other uses.

**Comment by an7oine** [comment]
That's why it has try/except. Does not break and does not require anything.

**Comment by djm** [comment]
It's still library specific code for something we don't have a dependency on.

If you subclass the middleware in your own code, you can override the method and provide your own functionality.

**Comment by an7oine** [comment]
I made another merge request that adds the ability to make the necessary addition in the inherited class.

**Pull request closed without merging**
